version: '3'
services:
  mysql:
    image: mysql:8.0.30-debian
    container_name: mysql_p
    volumes:
      - "./my.cnf:/etc/mysql/my.cnf"  
      #- "./data:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-test}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-test}"
      MYSQL_USER: "${MYSQL_USER:-test}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-test}"


# For testing, launch with:
#
# docker-compose up
# mysql -h '127.0.0.1' -P 3306  -u test -p'test' test 


# For production, change the following variables:
#
# export MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
# export MYSQL_DATABASE=MYSQL_DATABASE
# export MYSQL_USER=MYSQL_USER
# export MYSQL_PASSWORD=MYSQL_PASSWORD
# docker-compose up -d
# mysql -h '127.0.0.1' -P 3306  -u $MYSQL_USER -p'$MYSQL_PASSWORD' $MYSQL_DATABASE
